#! /usr/bin/env bash

# TODO... or not. 
# Turns out I'm not using PhpActor
# rm -rf $HOME/.local/phpactor
# rm -f /usr/local/bin/phpactor
# cd $HOME/.local
# git clone git@github.com:phpactor/phpactor
# cd phpactor
# composer install
# sudo ln -s $HOME/.local/phpactor/bin/phpactor /usr/local/bin/phpactor
