#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.fonts
cd $DOTFILES/fonts
unzip "*.zip" "*.ttf" "*.otf" -d $HOME/.fonts
rm -rf $DOTFILES/fonts/*/

rm -f $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.local/bin
rm -f $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# Switch Escape and Caps Lock
gsettings set org.gnome.desktop.input-sources xkb-options "['caps:swapescape']"
