#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.fonts
cd $DOTFILES/fonts
unzip "*.zip" "*.ttf" "*.otf" -d $HOME/.fonts
cd $DOTFILES/fonts && rm -rf */
