#! /usr/bin/env bash

# PhpActor
rm -rf $HOME/.local/phpactor
rm -f /usr/local/bin/phpactor
cd $HOME/.local
git clone git@github.com:phpactor/phpactor
cd phpactor
composer install
sudo ln -s $HOME/.local/phpactor/bin/phpactor /usr/local/bin/phpactor
