#!/usr/bin/env bash

if [ $# -lt 1 ]; then
  echo "Usage: $0 <on|off>"
  exit 1
fi

arg=$(echo "$1")

case "$arg" in
    on)
        state=true
        ;;
    off)
        state=false
        ;;
    *)
        echo "Invalid argument: '$1' (expected 'on' or 'off')" >&2
        exit 1
        ;;
esac

if $state; then
  su -c 'echo 40 > /sys/class/backlight/nv_backlight/brightness'
else
  echo 'Display will shutoff in 3 seconds.'
  echo "To turn back on, ssh into this machine and run 'mac_display on'."
  sleep 3
  su -c 'echo 0 > /sys/class/backlight/nv_backlight/brightness'
fi
