#!/usr/bin/env bash

# Credit to ThePrimeagen & Jess Archer
# Script for Tmux to allow for easier session-naming based on directories

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # Pruned: dot directories (caches, plugin trees) and ~/Library on macOS,
    # which is slow to walk and trips the Desktop/Documents privacy prompts.
    items=`find ~ -maxdepth 3 -mindepth 1 \( -path ~/Library -o -name '.*' \) -prune -o -type d -print`
    # items+=`echo -e "\n~/"`
    selected=`echo "$items" | fzf`
fi

dirname=`basename $selected | sed 's/\./_/g'`

tmux switch-client -t =$dirname
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c $selected -d -s $dirname && tmux switch-client -t $dirname || tmux new -c $selected -A -s $dirname
