#!/usr/bin/env bash

INIT_SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
DOTFILES="${INIT_SCRIPT_DIR}/../.."

# Ensure there is a config directory
[ -d "$HOME/.config" ] || mkdir -p "$HOME/.config"

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.fonts
cd $DOTFILES/fonts
unzip "*.zip" "*.ttf" "*.otf" -d $HOME/.fonts
rm -rf $DOTFILES/fonts/*/

rm -f $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.local/bin
rm -f $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim
echo desktop > "$HOME/.dotfiles-profile"

# Switch Escape and Caps Lock
gsettings set org.gnome.desktop.input-sources xkb-options "['caps:swapescape']"

# Handle uncommitted secrets file
if [ -f $DOTFILES/.secrets ]; then
    rm -f $HOME/.local/.secrets
    ln -s $DOTFILES/.secrets $HOME/.local/.secrets
else
    echo 'WARNING: Add .secrets file in directory to properly set env vars'
fi
