#!/usr/bin/env bash

INIT_SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
DOTFILES="${INIT_SCRIPT_DIR}/../.."

rm -f usr/local/bin/marksman
sudo ln -s $DOTFILES/lsps/marksman-linux /usr/local/bin/marksman
