#!/usr/bin/env bash
set -e

APPIMAGE_URL="https://github.com/neovim/neovim/releases/download/v0.12.5/nvim-linux-x86_64.appimage"
LOCAL_BIN="$HOME/.local/bin"
NVIM_APPIMAGE="$LOCAL_BIN/nvim-linux-x86_64.appimage"
NVIM_EXTRACTED="$HOME/.local/nvim-app"

mkdir -p "$LOCAL_BIN"

if [ -L "$LOCAL_BIN/nvim" ]; then
  sudo rm "$LOCAL_BIN/nvim"
fi

rm -rf "$NVIM_EXTRACTED"

cd "$LOCAL_BIN"
curl -LO "$APPIMAGE_URL"
chmod u+x "$NVIM_APPIMAGE"

"$NVIM_APPIMAGE" --appimage-extract
mv squashfs-root "$NVIM_EXTRACTED"
ln -s "$NVIM_EXTRACTED/AppRun" "$LOCAL_BIN/nvim"

echo "✅ Neovim installed and symlinked to 'nvim'."
