#!/usr/bin/env bash

INIT_SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
DOTFILES="${INIT_SCRIPT_DIR}/../.."

# Ensure there is a config directory
[ -d "$HOME/.config" ] || mkdir -p "$HOME/.config"

rm -f $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.local/bin
rm -f $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t
rm -f $HOME/.local/bin/mac_display
ln -s $DOTFILES/scripts/mac_display $HOME/.local/bin/mac_display

rm -rf $HOME/.config/nvim

if [ -f $DOTFILES/nvim/lua/user/desktop-plugins.lua ]; then
    # Do nothing
    echo 'Already moved TTY plugin config over'
else
    mv $DOTFILES/nvim/lua/user/plugins.lua $DOTFILES/nvim/lua/user/desktop-plugins.lua
    mv $DOTFILES/nvim/lua/user/tty-plugins.lua $DOTFILES/nvim/lua/user/plugins.lua
fi
ln -s $DOTFILES/nvim $HOME/.config/nvim
