#!/usr/bin/env bash

INIT_SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
DOTFILES="${INIT_SCRIPT_DIR}/../.."

# Ensure there is a config directory
[ -d "$HOME/.config" ] || mkdir -p "$HOME/.config"

rm -f $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.local/bin
rm -f $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim
